config/routes.rb
CarSeller::Application.routes.draw do
  get "index_controller/index"

  resources :vehicles

  resources :customers

  resources :vehicle_types

  resources :brands

  root :to => 'index_controller#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :brand
  belongs_to :vehicle_type
  belongs_to :customer
  attr_accessible :name, :brand_id, :vehicle_type_id, :price, :km, :type_fuel, :year, :customer_id 
  validates_numericality_of :price, :only_float => false, :greater_than => 0
  validates_numericality_of :km, :greater_than_or_equal_to => 0
  validates_presence_of :type_fuel
  validates_presence_of :year
  dollarizeme :price
  
	def full_name
		"#{brand.name} - #{name} (#{vehicle_type.name})"	
	end

def amount_in_pesos #metodo para cambiar en pesos
 d=Dollar.find(:first, :params => {:dollar_type => 1})
((price || 0) * d.buyer).to_s
end


end

app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base
	has_many :vehicles
	has_many :customers, :through => :vehicles
  attr_accessible :name
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
    @accessories = Accessory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(params[:vehicle])

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
def title(vehicle)
"<strong>#{vehicle.brand.name}</strong> - #{vehicle.name} <em>(#{vehicle.vehicle_type.name})</em>".html_safe
end
def dolar_oficial_compra
Dollar.find(:first, :params => {:dollar_type => 1}).buyer
end
def dolar_oficial_venta
Dollar.find(:first, :params => {:dollar_type => 1}).seller
end
def dolar_blue_compra
Dollar.find(:first, :params => {:dollar_type => 2}).buyer
end
def dolar_blue_venta
Dollar.find(:first, :params => {:dollar_type => 2}).seller
end

def dolar_green_compra
Dollar.find(:first, :params => {:dollar_type => 3}).buyer
end

def dolar_gold_compra
Dollar.find(:first, :params => {:dollar_type => 4}).buyer
end

def dolar_colonia_compra
Dollar.find(:first, :params => {:dollar_type => 5}).buyer
end

def dolar_miami_compra
Dollar.find(:first, :params => {:dollar_type => 6}).buyer
end



def accessory_name
 Accessory.find(:first, :params => [:name]).name.to_s
end

def accessory_price
 Accessory.find(:first, :params => [:price]).price.to_s
end

def accessory_Description
 Accessory.find(:first, :params => [:description]).Description.to_s
end

end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "errores encontrados") %> ! No se pudo guardar!</h2>
      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    Nombre<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Marca<br />
    <%= f.collection_select :brand_id, Brand.all, :id, :name %>
  </div>
  <div class="field">
    Tipo de vehiculo<br />
    <%= f.collection_select :vehicle_type_id, VehicleType.all, :id, :name %>
  </div>
  <div class="field">
    Dueño<br />
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    Precio<br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    Kilometros (sin puntos ni comas)<br />
    <%= f.text_field :km %>
  </div>
  <div class="field">
    Tipo de combustible<br />
    <%= f.text_field :type_fuel %>
  </div>
  <div class="field">
    Año<br />
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h2>Edicion de vehiculo</h2>

<%= render 'form' %>

<%= link_to 'Volver', vehicles_path, class: 'btn btn-inverse' %>

app/views/vehicles/index.html.erb
<h4>Lista de vehiculos</h4>




<table class="table table-hover table-striped">
  <tr>
    <th><h4> Dolar oficial compra <%=dolar_oficial_compra%>   </h4></th>
    <th> <h4> Dolar blue compra <%=dolar_blue_compra%>   </h4> </th>
   
    
  </tr>
   <tr>
   <th><h4> Dolar oficial venta <%=dolar_oficial_venta%>   </h4></th>
    
    <th><h4> Dolar blue venta <%=dolar_blue_venta%>   </h4></th>
    
  </tr>

</table>




<table class="table table-hover table-striped">
  <tr>
    <th>Tipo</th>
    <th>Modelo</th>
    <th>Tipo</th>
    <th>Cliente</th>
    <th>Precio Dolar</th>
    <th>Precio Pesos</th>
    <th>Km</th>
    <th>Combustible</th>
    <th>Año</th>
    <th></th>
    <th></th>
  </tr>

  </tr>
<% @vehicles.each do |vehicle| %>
  <tr class="<%= cycle :success %> ">
    <td><%= vehicle.brand.name %></td>
    <td><%= vehicle.name %></td>
    <td><%= vehicle.vehicle_type.name %></td>
    <td><%= vehicle.customer.name %></td>
    <td><%= vehicle.price %></td>
    <td><%= vehicle.price_to_blue %></td>
     <td><%= vehicle.amount_in_pesos %></td>


     
    <td><%= vehicle.km %></td>
    <td><%= vehicle.type_fuel %></td>
    <td><%= vehicle.year %></td>

    <td><button class: 'btn btn-warning'><%= link_to 'Editar', edit_vehicle_path(vehicle) %></button></td>
    <td><button class: 'btn btn-danger'><%= link_to 'Eliminar', vehicle, method: :delete, data: { confirm: 'Esta seguro?' } %></button></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to icon('plus')+'Nuevo Vehiculo', new_vehicle_path, class: 'btn btn-success' %>


<table class="table table-hover table-striped">
  <tr>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Descripcion</th>
   
  </tr>

  </tr>
  <% @accessories.each do | a | %>
  <tr class="<%= cycle :success %> ">
    <td><%= a.name %></td>
    <td><%= a.price %></td>
    <td><%= a.Description %></td>
  
  </tr>
 <% end %>
  </tbody>
</table>

app/views/vehicles/new.html.erb
<h3>Nuevo vehiculo</h3>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= title(@vehicle) %></p>

<p>
  <%= strongify('Nombre:')%>
  <%= @vehicle.name %>
</p>

<p>
  <%= strongify('Marca:')%>
  <%= @vehicle.brand.name %>
</p>

<p>
  <%= strongify('Tipo:')%>
  <%= @vehicle.vehicle_type.name %>
</p>

<p>
  <%= strongify('Precio:')%>
  <%= @vehicle.price %>
</p>

<p>
  <%= strongify('Kilometros:')%>
  <%= @vehicle.km %>
</p>

<p>
  <%= strongify('Tipo de Combustible:')%>
  <%= @vehicle.type_fuel %>
</p>

<p>
  <%= strongify('Año:')%>
  <%= @vehicle.year %>
</p>

<p>
  <%= strongify('Dueño:')%>
  <%= @vehicle.customer.name %>
</p>


<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>