config/routes.rb
CarSeller::Application.routes.draw do
  get "index_controller/index"

  resources :vehicles

  resources :customers

  resources :vehicle_types

  resources :brands

  root :to => 'index_controller#index'

end

app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  # GET /vehicle_types
  # GET /vehicle_types.json
  def index
    @vehicle_types = VehicleType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicle_types }
    end
  end

  # GET /vehicle_types/1
  # GET /vehicle_types/1.json
  def show
    @vehicle_type = VehicleType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle_type }
    end
  end

  # GET /vehicle_types/new
  # GET /vehicle_types/new.json
  def new
    @vehicle_type = VehicleType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle_type }
    end
  end

  # GET /vehicle_types/1/edit
  def edit
    @vehicle_type = VehicleType.find(params[:id])
  end

  # POST /vehicle_types
  # POST /vehicle_types.json
  def create
    @vehicle_type = VehicleType.new(params[:vehicle_type])

    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully created.' }
        format.json { render json: @vehicle_type, status: :created, location: @vehicle_type }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicle_types/1
  # PUT /vehicle_types/1.json
  def update
    @vehicle_type = VehicleType.find(params[:id])

    respond_to do |format|
      if @vehicle_type.update_attributes(params[:vehicle_type])
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_types/1
  # DELETE /vehicle_types/1.json
  def destroy
    @vehicle_type = VehicleType.find(params[:id])
    @vehicle_type.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

app/views/vehicle_types/_form.html.erb
<%= form_for(@vehicle_type) do |f| %>
  <% if @vehicle_type.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h2><%= pluralize(@vehicle_type.errors.count, "error") %> No se pudo guardar!:</h2>

        <ul>
        <% @vehicle_type.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicle_types/edit.html.erb
<h1>Editing vehicle_type</h1>

<%= render 'form' %>

<%= link_to 'Volver', vehicle_types_path, class: 'btn btn-inverse' %>

app/views/vehicle_types/index.html.erb
<h3>Tipos de vehiculos</h3>

<table class="table table-hover table-striped">
  <tr>
    <th>Tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehicle_types.each do |vehicle_type| %>
  <tr class="<%= cycle :success %> ">
    <td><%= vehicle_type.name %></td>
    <td><button type="button" class: "btn btn-info"><%= link_to 'Ver', vehicle_type %></button></td>
    <td><button type="button" class: 'btn btn-warning'><%= link_to 'Editar', edit_vehicle_type_path(vehicle_type) %></button></td>
    <td><button type="button" class: 'btn btn-danger'><%= link_to 'Eliminar', vehicle_type, method: :delete, data: { confirm: 'Esta seguro?' } %></button></td>

  </tr>
<% end %>
</table>

<br />


<%= link_to icon('plus')+'Nuevo tipo de vehiculo', new_vehicle_type_path, class: 'btn btn-success' %>

app/views/vehicle_types/new.html.erb
<h3>Nuevo tipo de vehiculo</h3>

<%= render 'form' %>



<%= link_to 'Back', vehicle_types_path %>

app/views/vehicle_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vehicle_type.name %>
</p>


<%= link_to 'Edit', edit_vehicle_type_path(@vehicle_type) %> |
<%= link_to 'Back', vehicle_types_path %>