config/routes.rb
CarSeller::Application.routes.draw do
  get "index_controller/index"

  resources :vehicles

  resources :customers

  resources :vehicle_types

  resources :brands

  root :to => 'index_controller#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	#self.table_name => 'marcas'
	#self.primary_key => 'codmarca'
	has_many :vehicles
	has_many :customers, :through => :vehicles, :uniq => true
	attr_accessible :name

	def total_vehicles
		vehicles.size # => vehicles.count  	
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Volver',brands_path, class: 'btn btn-inverse' %>

app/views/brands/index.html.erb
<h3>Marcas</h3>

<table class="table table-hover table-striped">
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr class="<%= cycle :success %> ">
    <td><%= link_to brand.name, brand %> (<%= brand.total_vehicles %>)</td>
    <td><button type="button" class: "btn btn-warning"> <%= link_to 'Editar', edit_brand_path(brand) %></button></td>
    <td><button type="button" class: 'btn btn-danger'> <%= link_to 'Eliminar', brand, method: :delete, data: { confirm: 'Esta seguro?' } %> </button></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to icon('plus')+'Nueva Marca', new_brand_path, class: 'btn btn-success' %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brand.name %>
</p>

<ul>
	<% @brand.vehicles.each do|v| %>
	<li><%= v.name %></li>
	<% end -%>
</ul>

<p>
	<%= @brand.vehicle_ids.inspect %>
</p>

<ul>
	<% @brand.customers.each do|c| %>
	<li><%= c.name %></li>
	<% end -%>
</ul>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>